---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: version
    params: {bump: patch}
  - put: docker-image
    params:
      tag_as_latest: true
      tag: version/number
      build: git-concourse-build-docker-image
  - put: kubernetes-staging
    params:
      kubectl: get node

resources:
- name: git-concourse-build-docker-image
  type: git
  source:
    uri: https://github.com/linwenjun/concourse-demo.git
    branch: master
  check_every: 1m

- name: docker-image
  type: docker-image
  source:
    username: admin
    password: Harbor12345
    insecure_registries: ["10.0.67.135"]
    repository: "10.0.67.135/library/nginx-apline"

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:tws-system/concourse-semver.git
    branch: version
    file: version
    private_key: ((concourse-repo-private-key))

- name: kubernetes-staging
  type: kubernetes
  source:
    server: https://10.0.128.28:6443
    token: ((kubernetes-token))
    certificate_authority: ((certificate_authority))    