---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: version
    params: {bump: minor}
  - put: docker-image
    params:
      build: git-concourse-build-docker-image

resources:
- name: git-concourse-build-docker-image
  type: git
  source:
    uri: https://github.com/linwenjun/concourse-demo.git
    branch: master
  check_every: 1m

- name: docker-image
  type: docker-image
  source:
    username: admin
    password: Harbor12345
    insecure_registries: ["10.0.67.135"]
    repository: "10.0.67.135/library/nginx"
    tag: [version/number]

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:tws-system/concourse-semver.git
    branch: version
    file: version
    private_key: ((concourse-repo-private-key))